Count,Message,Traceback,Nodes
1,'NoneType' object has no attribute 'url',"  File ""/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/locust/user/task.py"", line 340, in run
    self.execute_next_task()
  File ""/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/locust/user/task.py"", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File ""/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/locust/user/task.py"", line 385, in execute_task
    task(self)
  File ""/Users/andrewnordstrom/Elk_Corgi/corgi-recommender-service/tests/locustfile_recommendations.py"", line 141, in discover_content
    with self.client.get(
         ^^^^^^^^^^^^^^^^
  File ""/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/locust/clients.py"", line 252, in get
    return self.request(""GET"", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/locust/clients.py"", line 196, in request
    url = request_before_redirect.url  # type: ignore
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
",local
